spring:
  datasource:
    url: jdbc:postgresql://localhost:10004/myboard
    username: raymond
    password: 12341234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always  # ?? schema.sql ??
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none   # ?? create, validate ?
    show-sql: true       # ??? ???? SQL? ???? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ??
    database-platform: org.hibernate.dialect.PostgreSQLDialect